### ISSUE TITLE
Explain the purpose of this tooling

### ISSUE THREAD

**Issue by bzg** [codegouvfr/awesome-codegouvfr-tooling#1]

**Comment by hjonin** [comment]
I have [updated the README.md](https://github.com/codegouvfr/awesome-codegouvfr-tooling/commit/855f8aeac0930d98620fbcc6052268dad5c63a5e), would it be enough for this version?

**Comment by bzg** [comment]
Yes, great.  I expect it to work with non-GitHub URLs, is it the case? If so, we can mention it and close this issue.

**Comment by hjonin** [comment]
It will when we'll be able to use our own instance. I'll create another issue.

**Comment by bzg** [comment]
Ok, thanks.

**Comment by bzg** [comment]
Oh but `curl http://localhost:3000/publiccode\?repository_url\=https://git.asonix.dog/asonix/activitystreams` works!

So I allow myself to update the README consequently.

**Comment by hjonin** [comment]
Oh, great! It is not often it goes this way (working whereas not expected) :laughing:

**Comment by bzg** [comment]
"Any tool should be useful in the expected way, but a truly great tool lends itself to uses you never expected."

ESR: https://homepages.cwi.nl/~steven/Talks/Css-tutorial/floppy-old/practical3.html
