### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'full_name')

### ISSUE THREAD

**Issue by ptitloup** [codegouvfr/awesome-codegouvfr-tooling#5]
J'ai essayé d'utiliser le générateur mais quand je lance la commande
de génération (requete curl) avec cette adresse : curl http://localhost:3000/publiccode?repository_url=https://github.com/EsupPortail/Esup-Pod/

 voici l'erreur générée :

    Server listening on port 3000
    TypeError: Cannot read properties of null (reading 'full_name')
        at ecosystemToPubliccodeMapping (/tmp/
    awesome-codegouvfr-tooling/tools.js:39:36)
        at Object.ecosystemToPubliccode (/tmp/
    awesome-codegouvfr-tooling/tools.js:114:28)
        at process.processTicksAndRejections (node:internal/process/
    task_queues:95:5)

**Comment by bzg** [comment]
Hello, je n'arrive pas à reproduire le problème avec `nodejs v18.19.0` - tu as bien lancé l'install ?

**Comment by ptitloup** [comment]
Hello, les tests ont été réalisé avec la version v21.7.2 de Node. Je teste avec la v18.19.0.

**Comment by ptitloup** [comment]
En effet, avec la version 18.19 de Node, tout semble bien fonctionner : 
```
user@38b1c9b511c2:/usr/src/app# curl http://localhost:3000/publiccode?repository_url=https://github.com/EsupPortail/Esup-Pod/
publiccodeYmlVersion: "0.2"
name: EsupPortail/Esup-Pod
url: https://github.com/EsupPortail/Esup-Pod/
landingURL: ""
creationDate: 2018-02-19
latestRelease:
  date: ""
  version: ""
latestCommitDate: 2024-04-05
latestTestedInstallationDate: ""
logo: https://github.com/EsupPortail.png
usedBy: []
fundedBy:
  - name: ""
    url: ""
roadmap: ""
softwareType: ""
packages: []
description:
  en:
    shortDescription: "plateforme de gestion de fichier vidéo "
    documentation: ""
legal:
  license: lgpl-3.0
  authorsFile: ""
authors:
  distinctAuthorsCount: 0
  distinctOrganizationsCount: 0
maintenance:
  type: internal
  contacts:
    - email: ""
metadataFiles:
  readme: README.md
  license: COPYING
  contributing: CONTRIBUTING.md
  changelog: null
  codeOfConduct: CODE_OF_CONDUCT.md
  governance: null
lastUpdated: 2024-04-09
awesomeShield: https://img.shields.io/badge/awesome-codegouvfr_6/10-blue
